# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FourSquare-App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FourSquare-App
    #Alamofire
    pod 'Alamofire'
    pod 'AlamofireImage'
    #SQLite
    pod 'SQLite.swift', '~> 0.11.5'
    #ReactiveX
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    #SwiftyJSON
    pod 'SwiftyJSON', '~> 4.0'

end
